### ISSUE TITLE
awesome-wow-rust

### ISSUE THREAD

**Issue by arlyon** [Victov/wrath-rs#19]
Hi!

I have been working on azerust on and off (mostly off) as well as checking in here to see all the exciting progress, and decided it would be great to have a common hub to share resources for people working on wow-related projects in rust. I have added a list here: https://github.com/arlyon/awesome-wow-rust. Please consider opening a PR if you end up splitting out any crates, or if you want to flesh out any useful information on the readme entry. Maybe at some point a discord would be fun however this is very much a 'once every few months' type of passion project for me so for now I propose using discussions: https://github.com/arlyon/awesome-wow-rust/discussions

**Comment by Victov** [comment]
Hey @arlyon,

I am well aware that you are also doing wow related stuff in rust. I have been keeping an eye on azerust as well ;). I see you are already aware of the awesome work that @gtker is doing with his wow libraries. He also has some DBC reading libraries in rust that would be useful to add to your list.

This project is in the middle of a refactor to start using wow-messages instead of manually writing each packet. wow-messages is really awesome so I can recommend it! Which version of wow are you making a server for?

I have a chat on discord with @gtker every now and then (no server, just private chat) and as far as I'm concerned we can include you in that, if you're interested. If you'd like, drop your discord username.

**Comment by arlyon** [comment]
Sure! lalalastab#5782

**Comment by arlyon** [comment]
I have set up a server actually, see here: https://discord.gg/RjSytaEuuX
