### ISSUE TITLE
Opcode error spam from normal client sitting idle in-game

### ISSUE THREAD

**Issue by bigglesss** [Victov/wrath-rs#30]
After a few minutes of idle time, the server starts to spam errors about opcode 257 (0x101), or `CMSG_STANDSTATE_UPDATE`:

```
[...]
17-10-2022 10:25:01  WARN wrath_worldserver::client: Error in opcode: Opcode { opcode: 257, size: 4 }.
17-10-2022 10:25:01  WARN wrath_worldserver::client: Error in opcode: Opcode { opcode: 257, size: 4 }.
17-10-2022 10:25:01  WARN wrath_worldserver::client: Error in opcode: Opcode { opcode: 257, size: 4 }.
17-10-2022 10:25:01  WARN wrath_worldserver::client: Error in opcode: Opcode { opcode: 257, size: 4 }.
17-10-2022 10:25:01  WARN wrath_worldserver::client: Error in opcode: Opcode { opcode: 257, size: 4 }.
17-10-2022 10:25:01  WARN wrath_worldserver::client: Error in opcode: Opcode { opcode: 257, size: 4 }.
[...]
```

Given that there's also a SMSG_STANDSTATE_UPDATE, perhaps the client is expecting a response and spams until it gets it?

**Comment by Victov** [comment]
Ah yeah that makes sense. After some time of inactivity, your character goes into AFK mode and wants to sit down. I suspect it keeps spamming that opcode until it receives a response. 

I'll see about implementing that packet relatively soon. I have all the backbone in place to modify the stand state, so it should be a relatively easy fix.

The opcode being formatted as a number instead of a parsed packet does indicate that it's not available in wow_messages yet for wrath, so that will generate some wow_messages changes first.
